# -*- coding: utf-8 -*-
from pathlib import Path
from PIL import Image
import json,html
R=Path(__file__).resolve().parents[2];O=R/'docs/highlight-collage-demo';m=json.loads((O/'manifest.json').read_text());ref=O/'references';ref.mkdir(exist_ok=True)
for e in m['renders']:
 p=Path('/Users/uk/Downloads')/e['reference'];out=ref/(p.stem+'.jpg')
 if not out.exists():
  im=Image.open(p).convert('RGB');im.thumbnail((500,750));im.save(out,quality=80)
priority=['3902','3903','3904','3905','3907','3908','3877','3871','3872','3898','3878','3895','3897','3885','3887','3889','3894'];m['renders'].sort(key=lambda e:priority.index(e['id']) if e['id'] in priority else 99)
styles='''*{box-sizing:border-box}body{margin:0;background:#f2efe9;color:#242522;font:15px -apple-system,BlinkMacSystemFont,"Hiragino Sans",sans-serif}header{padding:42px 5vw 28px;border-bottom:1px solid #d4d1ca}small{letter-spacing:.14em;color:#62675b}h1{font-size:clamp(26px,4vw,48px);letter-spacing:-.04em;margin:12px 0}p{line-height:1.85;max-width:1000px}.toolbar{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-top:20px}button,select,a.btn{font:inherit;border:1px solid #b6bbae;background:white;padding:10px 16px;border-radius:25px;color:inherit;cursor:pointer;text-decoration:none}button.primary{background:#354a3a;color:white;border-color:#354a3a}#grid{padding:32px 5vw;display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:36px 22px}.card{min-width:0}.poster{display:block;width:100%;aspect-ratio:9/16;object-fit:contain;background:#ddd;box-shadow:0 6px 22px #0001;border-radius:4px;cursor:pointer}.name{font-weight:600;margin:14px 0 7px}.meta{font-size:12px;color:#5e645e;line-height:1.65}.card button{font-size:13px;padding:7px 13px;margin:10px 4px 0 0}dialog{border:0;border-radius:14px;width:min(1180px,95vw);max-height:94vh;background:#edeae4;padding:24px}dialog::backdrop{background:#101511dc}.review{display:grid;grid-template-columns:minmax(250px,1fr) minmax(250px,1fr) 240px;gap:20px;align-items:start}.review img,.review video{width:100%;max-height:77vh;object-fit:contain;background:#d7d5cd}.review h2{margin:0 0 10px;font-size:20px}.close{float:right;margin-bottom:12px}a{color:#405a45}#video{display:none}.note{padding:13px 17px;border-left:3px solid #ac9f79;background:#e8e3d8;font-size:13px}footer{padding:25px 5vw;color:#666} @media(max-width:800px){.review{grid-template-columns:1fr 1fr}.review aside{grid-column:1/-1}.review img,.review video{max-height:65vh}}'''
script='''const data=MANIFEST;let variant=false,current=0,artwork=false;const $=s=>document.querySelector(s);const cards=$('#grid');
function stillFile(e){return (artwork?'plates/'+e.id+(variant?'-color':'')+'.jpg':e[variant?'color':'original'].file)+'?rev=11'}
function render(){cards.innerHTML=data.map((e,i)=>`<article class="card"><img class="poster" src="${stillFile(e)}" alt="${e.id} ${e.name} の構図デモ" loading="lazy" data-review="${i}"><div class="name">${e.id} · ${e.name}</div><div class="meta">${e.reference}${e.panel?' ／ パネル '+e.panel:''} · ${e.original.sourceFrameIds.length}カット · ${e.layoutRevision===3?'部位認識を使用／改訂3':'従来の試作'}</div><button data-review="${i}">参照と比較</button><button data-play="${i}">動画デモ</button></article>`).join('')}
function review(i,play=false){current=i;const e=data[i];$('#title').textContent=e.id+' · '+e.name;$('#revision').textContent=e.layoutRevision===3?'顔ランドマークと肩位置を使用。書体は縦横変形なし。':'この案は部位認識・質感の精密な反映前です。';$('#reference').src='references/'+e.reference.split('.')[0]+'.jpg';$('#still').src=stillFile(e);$('#download').href='videos/'+e.id+'.mp4';$('#video').pause();$('#video').removeAttribute('src');$('#video').style.display=play?'block':'none';$('#still').style.display=play?'none':'block';if(play){$('#video').src='videos/'+e.id+'.mp4?rev=11';$('#video').play().catch(()=>{})}if(!$('#modal').open)$('#modal').showModal()}
cards.onclick=e=>{const r=e.target.closest('[data-review]'),p=e.target.closest('[data-play]');if(r)review(+r.dataset.review);if(p)review(+p.dataset.play,true)};
$('#artwork').onchange=e=>{artwork=e.target.checked;render();if($('#modal').open)review(current)};
$('#color').onchange=e=>{variant=e.target.value==='color';render()};
function uniform(n){const a=new Uint32Array(1),limit=Math.floor(4294967296/n)*n;do{crypto.getRandomValues(a)}while(a[0]>=limit);return a[0]%n}
$('#random').onclick=()=>{variant=!!uniform(2);$('#color').value=variant?'color':'original';render();review(uniform(data.length))};
$('#close').onclick=()=>$('#modal').close();$('#modal').onclose=()=>$('#video').pause();$('#play').onclick=()=>review(current,true);$('#compare').onclick=()=>review(current,false);$('#next').onclick=()=>review((current+1)%data.length);render();'''.replace('MANIFEST',json.dumps(m['renders'],ensure_ascii=False))
page=f'''<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>空手 · コラージュとハイライト構図デモ</title><style>{styles}</style><header><small>アランの空手・構図検討・第九版</small><h1>枠ごとに、顔・目・身体を配置する。</h1><p>35参照を、35枚のコラージュとして再構成。人物数、顔の部位、切り抜き、文字との前後関係、余白、粒子を個別に見直しました。3895は9マスで1枚、3897は6マスで1枚です。「構図だけを見る」でHookの下のデザインも比較できます。</p><p class="note">第0フレームから元動画の代わりにコラージュを表示し、中央にHook全文を3行同時に表示します。右下は縦1本のハイライトです。確認用にHookを4秒表示し、その間も3／3／4秒の再生は進みます。終了位置から拡大し、10秒で本編へ。テスト動画冒頭の声を使用し、先頭の無音0.2645秒を除いて0秒から再生します。3行は0秒から同時表示し、Hookの終了は確認用の4秒です。コラージュは背景切り抜き、小窓・本編は入力済み録画を使用しており、実際の「かくす」設定との接続は未実施です。共通Swift部品は追加しましたが、本番書き出しへの接続とiPhone実機性能の確認はこれからです。白黒・紙色を保ち、参照の色相差と彩度・明度の序列を維持して明るく調整。色相は共通角度で抽選。Hookは既存の丸ゴシックを維持し、承認済みの1番（普通・黒・淡色）または6番（淡色・黒・普通）を使用。中央は黒、上下は主色と白40％の淡色。組み合わせは動画中固定。装飾英字は日本語、数字は録画日付に置換。配色・乙は静止画のみ。</p><div class="toolbar"><select id="color" aria-label="配色見本"><option value="original">ランダム配色・甲</option><option value="color">ランダム配色・乙</option></select><label><input type="checkbox" id="artwork"> 構図だけを見る</label><button class="primary" id="random">35案 × ランダム配色の見本から抽選</button><a class="btn" href="glossy-demo/">Glossy・丸文字・Hook比較</a><a class="btn" href="3903-review/">3903の配色・濃淡比較</a><a class="btn" href="hue-demo/">3907の色相回転・色面加工</a><a class="btn" href="hook-variants/">Hookの白・重なり比較</a><a class="btn" href="checks/character-assets.jpg">全身キャラ素材</a><a class="btn" href="PLAN.md">実装・最適化プラン</a><a class="btn" href="TEMPLATES.md">参照画像との対応表</a><a class="btn" href="checks/recognized-parts.jpg">部位認識の確認</a></div></header><main id="grid"></main><dialog id="modal"><button id="close" class="close">閉じる ×</button><div style="clear:both" class="review"><section><h2>参照画像</h2><img id="reference" alt="ユーザー提供のデザイン参照"></section><section><h2>録画素材のデモ</h2><img id="still" alt="コラージュのFirst Frame"><video id="video" controls playsinline preload="none"></video></section><aside><h2 id="title"></h2><p id="revision" class="note"></p><p>0〜3秒：Hook＋小窓のハイライト1<br>3〜4秒：Hook＋小窓のハイライト2<br>4秒：同じ位置から拡大<br>4〜6秒：ハイライト2の続き<br>6〜10秒：ハイライト3<br>10秒〜：本編と現在位置</p><p class="meta">拡大中もハイライトの時計は止めず、再生し直しません。元動画の焼き込み済み装飾は残っています。元画像の人物・文章・署名はコラージュ出力に使用していません。</p><button id="play">動画を再生</button><button id="compare">静止画で比較</button><button id="next">次の案 →</button><p><a id="download" download>MP4を開く／保存</a></p></aside></div></dialog><footer>ローカルの比較用デモ。録画・参照画像の外部送信は行っていません。デモ解像度540×960、30fps。本番の画質設定とは別です。</footer><script>{script}</script></html>'''
(O/'index.html').write_text(page)
print('gallery generated')
